# Generated by Django 4.1.2 on 2022-11-26 03:55

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_pedido_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='ubicacion',
            field=djgeojson.fields.PointField(default='', verbose_name='Ingrese su ubicación: '),
        ),
    ]
