# Generated by Django 4.1.2 on 2022-11-26 03:56

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_pedido_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='ubicacion',
            field=djgeojson.fields.PointField(default={}, verbose_name='Ingrese su ubicación: '),
        ),
    ]
