# Generated by Django 4.1.2 on 2022-11-26 04:00

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_pedido_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='ubicacion',
            field=djgeojson.fields.PointField(blank=True, null=True, verbose_name='Ingrese su ubicación: '),
        ),
    ]
