# Generated by Django 4.1.2 on 2022-11-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_pedido_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(blank=True, choices=[('p', 'Pendiente'), ('e', 'Entregado'), ('c', 'En Camino')], default='p', help_text='Estado del Pedido', max_length=1),
        ),
    ]
