# Generated by Django 4.1.3 on 2022-11-24 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 11, 24)),
        ),
    ]
