# Generated by Django 4.1.2 on 2022-11-24 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 11, 24, 21, 39, 8, 459415, tzinfo=datetime.timezone.utc)),
        ),
    ]
