# Generated by Django 4.1.2 on 2022-11-24 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cartitem_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
